from dataclasses import dataclass
from pathlib import Path

from Generator.config import CpuConfig
from Generator.region import Region, Translation
from Generator.sv_utils import SystemVerilog
from Generator.template import TemplateContext


@dataclass(frozen=True)
class MemoryMapRenderer:
    config: CpuConfig
    config_path: Path
    template_path: Path

    def render(self, template: str) -> str:
        return self.create_context().render(template)

    def create_context(self) -> TemplateContext:
        memory_map = self.config.memory_map
        return TemplateContext(
            generated_notice=(
                "// This file is generated by Generator/cpu_generator.py from "
                f"{self.config_path.name} and {self.template_source_name()}.\n"
                "// Do not edit this file directly."
            ),
            instruction_reset_vector=SystemVerilog.sized_hex_literal(
                self.config.instruction_reset_vector,
                32,
            ),
            pc_goal=SystemVerilog.sized_hex_literal(self.config.pc_goal, 32),
            narrow_pc_define=(
                "`define RSD_NARROW_PC" if memory_map.pc.narrow else ""
            ),
            pc_width=str(memory_map.pc.width),
            physical_address_width=str(memory_map.physical_address_width),
            memory_map_doc=self.render_memory_map_doc(),
            memory_map_constants=self.render_region_constants(),
            get_memory_map_type_body=self.render_get_memory_map_type(),
            to_physical_address_body=self.render_to_physical_address(),
        )

    def template_source_name(self) -> str:
        try:
            return self.template_path.relative_to(self.config_path.parent).as_posix()
        except ValueError:
            return self.template_path.as_posix()

    def render_memory_map_doc(self) -> str:
        return "\n".join(
            f"//       {SystemVerilog.comment_address(region.logical_base, 32)} "
            f"--{SystemVerilog.comment_address(region.logical_end - 1, 32)}: "
            f"{region.name}"
            for region in self.config.memory_map.regions
        )

    def render_region_constants(self) -> str:
        return "\n\n".join(
            self.render_single_region_constants(region)
            for region in self.config.memory_map.regions
        )

    def render_single_region_constants(self, region: Region) -> str:
        logical_prefix = region.constants.logical_prefix
        physical_prefix = region.constants.physical_prefix
        physical_begin, physical_end = region.physical_range
        raw_width = self.config.memory_map.raw_address_width
        lines = [
            "//",
            f"// {region.name}",
            f"// logical [{SystemVerilog.comment_address(region.logical_base, 32)} - "
            f"{SystemVerilog.comment_address(region.logical_end - 1, 32)}] -> physical "
            f"[{SystemVerilog.comment_address(physical_begin, raw_width)} - "
            f"{SystemVerilog.comment_address(physical_end, raw_width)}]",
            "//",
            f"localparam {logical_prefix}_BASE = "
            f"{SystemVerilog.logical_address(region.logical_base)};",
        ]
        for register in region.registers:
            lines.append(
                f"localparam {logical_prefix}_{register.name:<7} = "
                f"{logical_prefix}_BASE + {register.offset};"
            )
        lines.extend(
            [
                f"localparam {logical_prefix}_BEGIN = {logical_prefix}_BASE;",
                f"localparam {logical_prefix}_END   = "
                f"{logical_prefix}_BASE + {region.size};",
                f"localparam {logical_prefix}_ADDR_BIT_WIDTH = "
                f"{region.address_bit_width};",
                f"localparam {physical_prefix}_BASE = "
                f"{SystemVerilog.physical_address(region.physical_base, raw_width)};",
            ]
        )
        for register in region.registers:
            lines.append(
                f"localparam {physical_prefix}_{register.name:<7} = "
                + self.translation_expression(
                    region,
                    f"{logical_prefix}_{register.name}",
                )
                + ";"
            )
        return "\n".join(lines)

    def render_get_memory_map_type(self) -> str:
        lines: list[str] = []
        for index, region in enumerate(self.config.memory_map.regions):
            prefix = "if" if index == 0 else "else if"
            lines.extend(
                [
                    f"    {prefix} ({self.range_condition(region, 'addr')}) begin",
                    f"        return {region.region_type.memory_map_type};",
                    "    end",
                ]
            )
        return "\n".join(lines)

    def render_to_physical_address(self) -> str:
        lines: list[str] = []
        for index, region in enumerate(self.config.memory_map.regions):
            prefix = "if" if index == 0 else "else if"
            lines.append(
                f"    {prefix} ({self.range_condition(region, 'logAddr')}) begin"
            )
            if not region.is_io:
                lines.append(f"        // {region.name}")
            lines.extend(
                [
                    f"        phyAddr.isUncachable = "
                    f"{SystemVerilog.boolean(region.uncachable)};",
                    f"        phyAddr.isIO = {SystemVerilog.boolean(region.is_io)};",
                    "        phyAddr.addr = "
                    + self.translation_expression(region, "logAddr")
                    + ";",
                    "    end",
                ]
            )
        return "\n".join(lines)

    @staticmethod
    def range_condition(region: Region, address: str) -> str:
        begin = region.logical_constant("BEGIN")
        end = region.logical_constant("END")
        return f"{begin} <= {address} && {address} < {end}"

    @staticmethod
    def translation_expression(
        region: Region,
        logical_address: str,
    ) -> str:
        physical_base = region.physical_constant("BASE")
        if region.translation is Translation.RELATIVE:
            logical_base = region.logical_constant("BEGIN")
            return (
                f"{physical_base} + "
                f"PhyRawAddrPath'({logical_address} - {logical_base})"
            )
        if region.address_bit_width == 0:
            return physical_base

        width = region.logical_constant("ADDR_BIT_WIDTH")
        return f"{physical_base} + PhyRawAddrPath'({logical_address}[{width}-1:0])"
