[project]
name = "rsd"
version = "0.1.0"
[build]
reset_type = "async_high"
sources = [
    "MicroArchConf.veryl",
    "BasicTypes.veryl",
    "Memory/MemoryMapTypes.veryl",
    "RenameLogic/ActiveListIndexTypes.veryl",
    "Cache/CacheSystemTypes.veryl",
    "Memory/MemoryTypes.veryl",
    "Decoder/OpFormat.veryl",
    "Decoder/MicroOp.veryl",
    "RegisterFile/BypassTypes.veryl",
    "FetchUnit/FetchUnitTypes.veryl",
    "FloatingPointUnit/FPUTypes.veryl",
    "LoadStoreUnit/LoadStoreUnitTypes.veryl",
    "RenameLogic/RenameLogicTypes.veryl",
    "Scheduler/SchedulerTypes.veryl",
    "Pipeline/PipelineTypes.veryl",
    "IO/IO_UnitTypes.veryl",
    "Privileged/CSR_UnitTypes.veryl",
    "MulDivUnit/MulDivUnitTypes.veryl",
    "Debug/DebugTypes.veryl",
    "Memory/Axi4LiteControlMemoryIF.veryl",
    "Memory/Axi4LiteControlRegisterIF.veryl",
    "Memory/Axi4MemoryIF.veryl",
    "Pipeline/FetchStage/NextPCStageIF.veryl",
    "Pipeline/FetchStage/FetchStageIF.veryl",
    "Pipeline/PreDecodeStageIF.veryl",
    "Pipeline/DecodeStageIF.veryl",
    "Pipeline/RenameStageIF.veryl",
    "Pipeline/DispatchStageIF.veryl",
    "Pipeline/ScheduleStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerIssueStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterReadStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerExecutionStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterWriteStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryIssueStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterReadStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryExecutionStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryAccessStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryTagAccessStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterWriteStageIF.veryl",
    "Pipeline/FPBackEnd/FPIssueStageIF.veryl",
    "Pipeline/FPBackEnd/FPRegisterReadStageIF.veryl",
    "Pipeline/FPBackEnd/FPExecutionStageIF.veryl",
    "Pipeline/CommitStageIF.veryl",
    "RegisterFile/RegisterFileIF.veryl",
    "RegisterFile/BypassNetworkIF.veryl",
    "MulDivUnit/MulDivUnitIF.veryl",
    "LoadStoreUnit/LoadStoreUnitIF.veryl",
    "LoadStoreUnit/AMOCacheIF.veryl",
    "FloatingPointUnit/FPDivSqrtUnitIF.veryl",
    "RenameLogic/RenameLogicIF.veryl",
    "RenameLogic/ActiveListIF.veryl",
    "Scheduler/SchedulerIF.veryl",
    "Scheduler/WakeupSelectIF.veryl",
    "Cache/CacheSystemIF.veryl",
    "Cache/DCacheIF.veryl",
    "Cache/CacheFlushManagerIF.veryl",
    "ControllerIF.veryl",
    "Recovery/RecoveryManagerIF.veryl",
    "Privileged/CSR_UnitIF.veryl",
    "IO/IO_UnitIF.veryl",
    "Debug/DebugIF.veryl",
    "Debug/PerformanceCounterIF.veryl",
    "SysDeps/Verilator/VerilatorHelper.veryl",
]
target = {type = "bundle", path = "target/rsd_pkg_if.sv"}
omit_project_prefix = true
