[project]
name = "rsd"
version = "0.1.0"
[build]
reset_type = "async_high"
filelist_type = "relative"
source = "."
sources = [
    "MicroArchConf.veryl",
    "BasicTypes.veryl",
    "Memory/MemoryMapTypes.veryl",
    "RenameLogic/ActiveListIndexTypes.veryl",
    "Cache/CacheSystemTypes.veryl",
    "Memory/MemoryTypes.veryl",
    "Decoder/OpFormat.veryl",
    "Decoder/MicroOp.veryl",
    "RegisterFile/BypassTypes.veryl",
    "FetchUnit/FetchUnitTypes.veryl",
    "FloatingPointUnit/FPUTypes.veryl",
    "LoadStoreUnit/LoadStoreUnitTypes.veryl",
    "RenameLogic/RenameLogicTypes.veryl",
    "Scheduler/SchedulerTypes.veryl",
    "Pipeline/PipelineTypes.veryl",
    "IO/IO_UnitTypes.veryl",
    "Privileged/CSR_UnitTypes.veryl",
    "MulDivUnit/MulDivUnitTypes.veryl",
    "Debug/DebugTypes.veryl",
    "Memory/Axi4LiteControlMemoryIF.veryl",
    "Memory/Axi4LiteControlRegisterIF.veryl",
    "Memory/Axi4MemoryIF.veryl",
    "Pipeline/FetchStage/NextPCStageIF.veryl",
    "Pipeline/FetchStage/FetchStageIF.veryl",
    "Pipeline/PreDecodeStageIF.veryl",
    "Pipeline/DecodeStageIF.veryl",
    "Pipeline/RenameStageIF.veryl",
    "Pipeline/DispatchStageIF.veryl",
    "Pipeline/ScheduleStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerIssueStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterReadStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerExecutionStageIF.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterWriteStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStageIF.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryIssueStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterReadStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryExecutionStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryAccessStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryTagAccessStageIF.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterWriteStageIF.veryl",
    "Pipeline/FPBackEnd/FPIssueStageIF.veryl",
    "Pipeline/FPBackEnd/FPRegisterReadStageIF.veryl",
    "Pipeline/FPBackEnd/FPExecutionStageIF.veryl",
    "Pipeline/CommitStageIF.veryl",
    "RegisterFile/RegisterFileIF.veryl",
    "RegisterFile/BypassNetworkIF.veryl",
    "MulDivUnit/MulDivUnitIF.veryl",
    "LoadStoreUnit/LoadStoreUnitIF.veryl",
    "LoadStoreUnit/AMOCacheIF.veryl",
    "FloatingPointUnit/FPDivSqrtUnitIF.veryl",
    "RenameLogic/RenameLogicIF.veryl",
    "RenameLogic/ActiveListIF.veryl",
    "Scheduler/SchedulerIF.veryl",
    "Scheduler/WakeupSelectIF.veryl",
    "Cache/CacheSystemIF.veryl",
    "Cache/DCacheIF.veryl",
    "Cache/CacheFlushManagerIF.veryl",
    "ControllerIF.veryl",
    "Recovery/RecoveryManagerIF.veryl",
    "Privileged/CSR_UnitIF.veryl",
    "IO/IO_UnitIF.veryl",
    "Debug/DebugIF.veryl",
    "Debug/PerformanceCounterIF.veryl",
    "SysDeps/Verilator/VerilatorHelper.veryl",
    "Core.veryl",
    "Pipeline/FetchStage/NextPCStage.veryl",
    "Pipeline/FetchStage/FetchStage.veryl",
    "Pipeline/FetchStage/PC.veryl",
    "Pipeline/PreDecodeStage.veryl",
    "Pipeline/DecodeStage.veryl",
    "Pipeline/RenameStage.veryl",
    "Pipeline/DispatchStage.veryl",
    "Pipeline/ScheduleStage.veryl",
    "Pipeline/IntegerBackEnd/IntegerIssueStage.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterReadStage.veryl",
    "Pipeline/IntegerBackEnd/IntegerExecutionStage.veryl",
    "Pipeline/IntegerBackEnd/IntegerRegisterWriteStage.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerIssueStage.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterReadStage.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerExecutionStage.veryl",
    "Pipeline/ComplexIntegerBackEnd/ComplexIntegerRegisterWriteStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryIssueStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterReadStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryExecutionStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryAccessStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryTagAccessStage.veryl",
    "Pipeline/MemoryBackEnd/MemoryRegisterWriteStage.veryl",
    "Pipeline/FPBackEnd/FPIssueStage.veryl",
    "Pipeline/FPBackEnd/FPRegisterReadStage.veryl",
    "Pipeline/FPBackEnd/FPExecutionStage.veryl",
    "Pipeline/FPBackEnd/FPRegisterWriteStage.veryl",
    "Pipeline/CommitStage.veryl",
    "RegisterFile/RegisterFile.veryl",
    "RegisterFile/BypassController.veryl",
    "RegisterFile/BypassNetwork.veryl",
    "ExecUnit/BitCounter.veryl",
    "ExecUnit/IntALU.veryl",
    "ExecUnit/Shifter.veryl",
    "ExecUnit/MultiplierUnit.veryl",
    "ExecUnit/PipelinedRefDivider.veryl",
    "ExecUnit/DividerUnit.veryl",
    "MulDivUnit/MulDivUnit.veryl",
    "LoadStoreUnit/LoadStoreUnit.veryl",
    "LoadStoreUnit/LoadQueue.veryl",
    "LoadStoreUnit/StoreQueue.veryl",
    "LoadStoreUnit/StoreCommitter.veryl",
    "LoadStoreUnit/AMOCache.veryl",
    "FloatingPointUnit/FP32PipelinedAdder.veryl",
    "FloatingPointUnit/FP32PipelinedMultiplier.veryl",
    "FloatingPointUnit/FP32PipelinedFMA.veryl",
    "FloatingPointUnit/FP32PipelinedOther.veryl",
    "FloatingPointUnit/FP32DivSqrter.veryl",
    "FloatingPointUnit/FPDivSqrtUnit.veryl",
    "RenameLogic/RenameLogic.veryl",
    "RenameLogic/ActiveList.veryl",
    "RenameLogic/RMT.veryl",
    "RenameLogic/RetirementRMT.veryl",
    "RenameLogic/RenameLogicCommitter.veryl",
    "Decoder/Decoder.veryl",
    "Decoder/DecodedBranchResolver.veryl",
    "FetchUnit/BTB.veryl",
    "FetchUnit/BranchPredictor.veryl",
    "FetchUnit/Gshare.veryl",
    "FetchUnit/Bimodal.veryl",
    "Scheduler/IssueQueue.veryl",
    "Scheduler/ReplayQueue.veryl",
    "Scheduler/DestinationRAM.veryl",
    "Scheduler/ReadyBitTable.veryl",
    "Scheduler/Scheduler.veryl",
    "Scheduler/SelectLogic.veryl",
    "Scheduler/SourceCAM.veryl",
    "Scheduler/WakeupLogic.veryl",
    "Scheduler/WakeupPipelineRegister.veryl",
    "Scheduler/ProducerMatrix.veryl",
    "Scheduler/MemoryDependencyPredictor.veryl",
    "Cache/DCache.veryl",
    "Cache/ICache.veryl",
    "Cache/MemoryAccessController.veryl",
    "Cache/CacheFlushManager.veryl",
    "Memory/Memory.veryl",
    "Memory/Axi4LiteControlRegister.veryl",
    "Memory/Axi4LiteMemory.veryl",
    "Memory/ControlQueue.veryl",
    "Memory/Axi4Memory.veryl",
    "Memory/MemoryReadReqQueue.veryl",
    "Memory/MemoryWriteDataQueue.veryl",
    "Memory/MemoryLatencySimulator.veryl",
    "Recovery/RecoveryManager.veryl",
    "Controller.veryl",
    "ResetController.veryl",
    "Privileged/InterruptController.veryl",
    "Privileged/CSR_Unit.veryl",
    "IO/IO_Unit.veryl",
    "Primitives/FlipFlop.veryl",
    "Primitives/FreeList.veryl",
    "Primitives/Queue.veryl",
    "Primitives/RAM.veryl",
    "Primitives/LRU_Counter.veryl",
    "Primitives/Picker.veryl",
    "Primitives/Multiplier.veryl",
    "Primitives/Divider.veryl",
    "Debug/Debug.veryl",
    "Debug/PerformanceCounter.veryl",
]
target = {type = "directory", path = "target/veryl"}
sourcemap_target = {type = "directory", path = "target/veryl-map"}
omit_project_prefix = true
exclude_std = true
