// Copyright 2019- RSD contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.

// This file is generated by Generator/cpu_generator.py from default.yml and Memory/MemoryMapTypes.template.sv.
// Do not edit this file directly.


// 
// --- Types related to a memory map
//

package MemoryMapTypes;

import BasicTypes::*;


//
// Related to instructions 
//
localparam INSN_RESET_VECTOR = 32'h00001000;

// The processor stops when it reaches PC_GOAL
localparam PC_GOAL = 32'h80001004;

//
// PC
//

 // This option compresses PC for reducing resource consumption.
`define RSD_NARROW_PC
// The PC compression is achieved by leveraging the memory map.
// The memory map in the logical address space is as follows.
//       0x0000_1000 --0x0000_ffff: Section 0 (ROM)
//       0x8000_0000 --0x8003_ffff: Section 1 (RAM)
//       0x8004_0000 --0x8004_ffff: Uncachable section (RAM)
//       0x4000_2000 --0x4000_2000: Serial IO
//       0x4000_0000 --0x4000_000f: Timer IO
// In this map, instruction access is not performed in the IO area, so
// the range of valid instructions is only in the ROM and RAM areas.
// The narrow PC format keeps the most significant bit and lower address bits.
// Note that when handling exceptions, it is necessary to handle with a 32-bit address.

`ifdef RSD_NARROW_PC
localparam PC_WIDTH = 19;
`else
localparam PC_WIDTH = ADDR_WIDTH;
`endif

localparam PC_TAG = ADDR_WIDTH - PC_WIDTH;
typedef logic [PC_WIDTH-1:0] PC_Path;

// 圧縮されたPCを32ビットアドレスに変換する
function automatic AddrPath ToAddrFromPC ( PC_Path pc );
`ifdef RSD_NARROW_PC
    return { pc[PC_WIDTH-1], { PC_TAG{1'b0} }, pc[PC_WIDTH-2:0] };
`else
    return pc;
`endif
endfunction

// 32ビットアドレスを圧縮する
function automatic PC_Path ToPC_FromAddr ( AddrPath addr );
`ifdef RSD_NARROW_PC
    return { addr[ADDR_WIDTH-1], addr [PC_WIDTH-2:0] };
`else
    return addr;
`endif
endfunction


//
// Logical address memory type
//
typedef enum logic[1:0]  {
    MMT_MEMORY  = 2'b00,
    MMT_IO      = 2'b01,
    MMT_ILLEGAL = 2'b10
} MemoryMapType;

//
// Physical Address
// The most significant two bits of the physical memory address is used distinguish between 
// accesses to a normal memory region, memory-mapped IO region, and uncachable region.
localparam PHY_ADDR_WIDTH = 22;  // 1bit uncachable flag + 1bit IO flag + raw memory space
localparam PHY_ADDR_WIDTH_BIT_SIZE = $clog2(PHY_ADDR_WIDTH);
localparam PHY_ADDR_BYTE_WIDTH = PHY_ADDR_WIDTH / BYTE_WIDTH;

localparam PHY_RAW_ADDR_WIDTH = PHY_ADDR_WIDTH - 2;
localparam PHY_RAW_ADDR_WIDTH_BIT_SIZE = $clog2(PHY_RAW_ADDR_WIDTH);
localparam PHY_RAW_ADDR_BYTE_WIDTH = PHY_RAW_ADDR_WIDTH / BYTE_WIDTH;

typedef logic [PHY_RAW_ADDR_WIDTH-1:0] PhyRawAddrPath;
typedef struct packed {
    logic isUncachable; // True if address points to an uncachable address space.
    logic isIO; // True if address points to a memory-mapped IO.
    PhyRawAddrPath addr;
} PhyAddrPath;


//
// Memory map between logical and physical address spaces
// 

//
// Section 0 (ROM)
// logical [0x0000_1000 - 0x0000_ffff] -> physical [0x0_1000 - 0x0_ffff]
//
localparam LOG_ADDR_SECTION_0_BASE = ADDR_WIDTH'('h0000_1000);
localparam LOG_ADDR_SECTION_0_BEGIN = LOG_ADDR_SECTION_0_BASE;
localparam LOG_ADDR_SECTION_0_END   = LOG_ADDR_SECTION_0_BASE + 61440;
localparam LOG_ADDR_SECTION_0_ADDR_BIT_WIDTH = 16;
localparam PHY_ADDR_SECTION_0_BASE = PHY_RAW_ADDR_WIDTH'('h0_0000);

//
// Section 1 (RAM)
// logical [0x8000_0000 - 0x8003_ffff] -> physical [0x1_0000 - 0x4_ffff]
//
localparam LOG_ADDR_SECTION_1_BASE = ADDR_WIDTH'('h8000_0000);
localparam LOG_ADDR_SECTION_1_BEGIN = LOG_ADDR_SECTION_1_BASE;
localparam LOG_ADDR_SECTION_1_END   = LOG_ADDR_SECTION_1_BASE + 262144;
localparam LOG_ADDR_SECTION_1_ADDR_BIT_WIDTH = 18;
localparam PHY_ADDR_SECTION_1_BASE = PHY_RAW_ADDR_WIDTH'('h1_0000);

//
// Uncachable section (RAM)
// logical [0x8004_0000 - 0x8004_ffff] -> physical [0x5_0000 - 0x5_ffff]
//
localparam LOG_ADDR_UNCACHABLE_BASE = ADDR_WIDTH'('h8004_0000);
localparam LOG_ADDR_UNCACHABLE_BEGIN = LOG_ADDR_UNCACHABLE_BASE;
localparam LOG_ADDR_UNCACHABLE_END   = LOG_ADDR_UNCACHABLE_BASE + 65536;
localparam LOG_ADDR_UNCACHABLE_ADDR_BIT_WIDTH = 19;
localparam PHY_ADDR_UNCACHABLE_BASE = PHY_RAW_ADDR_WIDTH'('h1_0000);

//
// Serial IO
// logical [0x4000_2000 - 0x4000_2000] -> physical [0x0_2000 - 0x0_2000]
//
localparam LOG_ADDR_SERIAL_BASE = ADDR_WIDTH'('h4000_2000);
localparam LOG_ADDR_SERIAL_OUTPUT  = LOG_ADDR_SERIAL_BASE + 0;
localparam LOG_ADDR_SERIAL_BEGIN = LOG_ADDR_SERIAL_BASE;
localparam LOG_ADDR_SERIAL_END   = LOG_ADDR_SERIAL_BASE + 1;
localparam LOG_ADDR_SERIAL_ADDR_BIT_WIDTH = 0;
localparam PHY_ADDR_SERIAL_BASE = PHY_RAW_ADDR_WIDTH'('h0_2000);
localparam PHY_ADDR_SERIAL_OUTPUT  = PHY_ADDR_SERIAL_BASE;

//
// Timer IO
// logical [0x4000_0000 - 0x4000_000f] -> physical [0x0_0000 - 0x0_000f]
//
localparam LOG_ADDR_TIMER_BASE = ADDR_WIDTH'('h4000_0000);
localparam LOG_ADDR_TIMER_LOW     = LOG_ADDR_TIMER_BASE + 0;
localparam LOG_ADDR_TIMER_HI      = LOG_ADDR_TIMER_BASE + 4;
localparam LOG_ADDR_TIMER_CMP_LOW = LOG_ADDR_TIMER_BASE + 8;
localparam LOG_ADDR_TIMER_CMP_HI  = LOG_ADDR_TIMER_BASE + 12;
localparam LOG_ADDR_TIMER_BEGIN = LOG_ADDR_TIMER_BASE;
localparam LOG_ADDR_TIMER_END   = LOG_ADDR_TIMER_BASE + 16;
localparam LOG_ADDR_TIMER_ADDR_BIT_WIDTH = 4;
localparam PHY_ADDR_TIMER_BASE = PHY_RAW_ADDR_WIDTH'('h0_0000);
localparam PHY_ADDR_TIMER_LOW     = PHY_ADDR_TIMER_BASE + PhyRawAddrPath'(LOG_ADDR_TIMER_LOW[LOG_ADDR_TIMER_ADDR_BIT_WIDTH-1:0]);
localparam PHY_ADDR_TIMER_HI      = PHY_ADDR_TIMER_BASE + PhyRawAddrPath'(LOG_ADDR_TIMER_HI[LOG_ADDR_TIMER_ADDR_BIT_WIDTH-1:0]);
localparam PHY_ADDR_TIMER_CMP_LOW = PHY_ADDR_TIMER_BASE + PhyRawAddrPath'(LOG_ADDR_TIMER_CMP_LOW[LOG_ADDR_TIMER_ADDR_BIT_WIDTH-1:0]);
localparam PHY_ADDR_TIMER_CMP_HI  = PHY_ADDR_TIMER_BASE + PhyRawAddrPath'(LOG_ADDR_TIMER_CMP_HI[LOG_ADDR_TIMER_ADDR_BIT_WIDTH-1:0]);


// Get a memory type from a logical address
function automatic MemoryMapType GetMemoryMapType(AddrPath addr);
    if (LOG_ADDR_SECTION_0_BEGIN <= addr && addr < LOG_ADDR_SECTION_0_END) begin
        return MMT_MEMORY;
    end
    else if (LOG_ADDR_SECTION_1_BEGIN <= addr && addr < LOG_ADDR_SECTION_1_END) begin
        return MMT_MEMORY;
    end
    else if (LOG_ADDR_UNCACHABLE_BEGIN <= addr && addr < LOG_ADDR_UNCACHABLE_END) begin
        return MMT_MEMORY;
    end
    else if (LOG_ADDR_SERIAL_BEGIN <= addr && addr < LOG_ADDR_SERIAL_END) begin
        return MMT_IO;
    end
    else if (LOG_ADDR_TIMER_BEGIN <= addr && addr < LOG_ADDR_TIMER_END) begin
        return MMT_IO;
    end
    else begin
        return MMT_ILLEGAL;
    end
endfunction

// Convert a logical address to a physical address
function automatic PhyAddrPath ToPhyAddrFromLogical(AddrPath logAddr);
    PhyAddrPath phyAddr;

    if (LOG_ADDR_SECTION_0_BEGIN <= logAddr && logAddr < LOG_ADDR_SECTION_0_END) begin
        // Section 0 (ROM)
        phyAddr.isUncachable = FALSE;
        phyAddr.isIO = FALSE;
        phyAddr.addr = PHY_ADDR_SECTION_0_BASE + PhyRawAddrPath'(logAddr[LOG_ADDR_SECTION_0_ADDR_BIT_WIDTH-1:0]);
    end
    else if (LOG_ADDR_SECTION_1_BEGIN <= logAddr && logAddr < LOG_ADDR_SECTION_1_END) begin
        // Section 1 (RAM)
        phyAddr.isUncachable = FALSE;
        phyAddr.isIO = FALSE;
        phyAddr.addr = PHY_ADDR_SECTION_1_BASE + PhyRawAddrPath'(logAddr[LOG_ADDR_SECTION_1_ADDR_BIT_WIDTH-1:0]);
    end
    else if (LOG_ADDR_UNCACHABLE_BEGIN <= logAddr && logAddr < LOG_ADDR_UNCACHABLE_END) begin
        // Uncachable section (RAM)
        phyAddr.isUncachable = TRUE;
        phyAddr.isIO = FALSE;
        phyAddr.addr = PHY_ADDR_UNCACHABLE_BASE + PhyRawAddrPath'(logAddr[LOG_ADDR_UNCACHABLE_ADDR_BIT_WIDTH-1:0]);
    end
    else if (LOG_ADDR_SERIAL_BEGIN <= logAddr && logAddr < LOG_ADDR_SERIAL_END) begin
        phyAddr.isUncachable = TRUE;
        phyAddr.isIO = TRUE;
        phyAddr.addr = PHY_ADDR_SERIAL_BASE;
    end
    else if (LOG_ADDR_TIMER_BEGIN <= logAddr && logAddr < LOG_ADDR_TIMER_END) begin
        phyAddr.isUncachable = TRUE;
        phyAddr.isIO = TRUE;
        phyAddr.addr = PHY_ADDR_TIMER_BASE + PhyRawAddrPath'(logAddr[LOG_ADDR_TIMER_ADDR_BIT_WIDTH-1:0]);
    end
    else begin
        // Invalid
        phyAddr.isUncachable = FALSE;
        phyAddr.isIO = FALSE;
        phyAddr.addr = 32'hCCCC_CCCC;
    end

    return phyAddr;
endfunction

function automatic logic IsPhyAddrIO(PhyAddrPath phyAddr);
    return phyAddr.isIO;
endfunction

function automatic logic IsPhyAddrUncachable(PhyAddrPath phyAddr);
    return phyAddr.isUncachable;
endfunction

endpackage
